#!/usr/bin/env ruby

ADDED_OR_MODIFIED = /A|AM|^M/.freeze

old_stash = `git rev-parse -q --verify refs/stash`
system("git stash -k -q")
new_stash = `git rev-parse -q --verify refs/stash`

if old_stash == new_stash
  puts "pre commit script: no changes to test"
  exit 0
end

changed_files = `git status --porcelain`.split(/\n/).
    select { |file_name_with_status|
      file_name_with_status =~ ADDED_OR_MODIFIED
    }.
    map { |file_name_with_status|
      file_name_with_status.split(' ')[1]
    }.
    select { |file_name|
      File.extname(file_name) == '.rb'
    }.join(' ')

system("bundle exec rubocop #{changed_files}") unless changed_files.empty?
result = $CHILD_STATUS.to_s[-1].to_i

system("git reset --hard -q ; git stash pop --index -q")

exit result
